image: gitpod/workspace-java-11 

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

tasks:
- init: mvn dependency:go-offline package -DskipTests
  command: java -jar target/*.jar
  name: run

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
