image: gitpod/workspace-java-17

vscode:
  extensions:
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-java-pack

tasks:
- init: mvn dependency:go-offline package -DskipTests
  command: java -jar target/*.jar
  name: run

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
